// src/components/Board.tsx
import { useKanban } from '../context/KanbanContext';
import type { Status } from '../types/kanban';

const COLUMN_COLORS = ['#49C4E5', '#8471F2', '#67E2AE', '#F4B550', '#E96E6E'];

const Board = () => {
  const { state, dispatch } = useKanban();
  const { boards, activeBoardIndex } = state;
  const activeBoard = boards[activeBoardIndex];

  return (
    <section className="h-full w-full bg-light-grey dark:bg-very-dark-grey overflow-auto">
      {activeBoard.columns.length === 0 ? (
        <div className="flex h-full items-center justify-center flex-col gap-6">
          <h2 className="text-medium-grey">This board is empty. Create a new column to get started.</h2>
          <button className="button-primary-l" onClick={() => dispatch({ type: 'TOGGLE_EDIT_BOARD_PANEL' })}>+ Add New Column</button>
        </div>
      ) : (
        <div className="flex gap-6 p-6 min-h-full w-max">
          {activeBoard.columns.map((column, index) => (
            <div key={column.name} className="flex flex-col gap-4 w-70 shrink-0">
              <div className="flex items-center gap-3">
                <span className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: COLUMN_COLORS[index % COLUMN_COLORS.length] }} />
                <p className="heading-s">{column.name.toUpperCase()} ({column.tasks.length})</p>
              </div>
              <div className="flex flex-col gap-4">
                {column.tasks.map(task => (
                  <div key={task.title} onClick={() => dispatch({ type: 'SELECT_TASK', payload: { ...task, status: column.name as Status } })} className="bg-white dark:bg-dark-grey rounded-lg p-4 shadow-sm cursor-pointer hover:opacity-80">
                    <h3 className="heading-m text-black dark:text-white">{task.title}</h3>
                    <p className="body-m text-medium-grey mt-2">
                      {task.subtasks.filter(s => s.isCompleted).length} of {task.subtasks.length} subtasks
                    </p>
                  </div>
                ))}
              </div>
            </div>
          ))}
          <div className="flex flex-col gap-4 shrink-0">
            <div className="invisible heading-s">placeholder</div>
            <button
              onClick={() => dispatch({ type: 'TOGGLE_EDIT_BOARD_PANEL' })}
              className='flex-1 bg-lines-light dark:bg-lines-dark/50 heading-m text-medium-grey rounded-md px-8 flex items-center gap-1 cursor-pointer hover:text-main-purple'
            >
              + New Column
            </button>
          </div>
        </div>
      )}
    </section>
  )
}

export default Board

// src/app/components/board/board.component.ts
import { Component, Input, OnInit, inject, signal } from '@angular/core';
import { BoardService } from '../../services/board.service';
import { Board } from '../../models/board.model';
import { UpperCasePipe, CommonModule } from "@angular/common";
import { ActivatedRoute, Router } from '@angular/router';
import { switchMap } from 'rxjs';
import { TaskComponent } from '../task/task.component';



@Component({
  selector: 'app-board',
  standalone: true,
  imports: [UpperCasePipe, CommonModule, TaskComponent],
  templateUrl: './board.component.html',
  styleUrl: './board.component.scss'
})
export class BoardComponent implements OnInit{

  @Input() name: string = '';

  board = signal<Board>({
    name: '',
    columns: []
  })
  private board_service = inject(BoardService);
  counter: number = 0;
  isModalTaskOpen: boolean = false;
  taskName: string = '';
  columnName: string = '';

  constructor(private route: ActivatedRoute){ }

  ngOnInit(){
    this.route.params.pipe(
      switchMap( ( {name} ) => {
        if (!name) {
          return this.board_service.getBoardByName('Platform Launch')
        }
        else{
          return this.board_service.getBoardByName(name)
        }
      })
    )
    .subscribe({
      next: (board: Board[]) => {
        this.board.set(board[0])
      }
    })
  }

  getColorForTasks(name: string){
    let color = '';
    switch (name) {
      case 'Todo':
        color = '#49C4E5';
        break;
      case 'Doing':
        color = '#8471F2';
        break;
      case 'Done':
        color = '#67E2AE';
        break;
      default:
        break;
    }
    return color;
  }

  toggleModalTasks(title: string, columnName: string){
    this.isModalTaskOpen = !this.isModalTaskOpen;
    this.taskName = title;
    this.columnName = columnName;
  }
}

<section class="ml-64 p-8 min-h-screen">
  @if (board().columns.length === 0) {
    <section class="flex flex-col justify-center items-center min-h-screen">
      <h4 class="h4">This board is empty. Create a new column to get started.</h4>
      <button class="button-primary-l mt-6">Add new column</button>
    </section>
  }
  @else {
    <section class="grid grid-cols-4 gap-x-4">
      @for (column of board().columns; track $index) {
        <section class="flex flex-col space-y-4 ">
          <div class="flex items-center">
            <div class="h-3 w-3 rounded-full" [style.background-color]="getColorForTasks(column.name)"></div>
            <h4 class="h4 ml-4">{{column.name | uppercase}} ({{column.tasks.length}})</h4>
          </div>
            @for (task of column.tasks; track $index) {
              <button class="p-6 bg-white rounded-md shadow-md text-start" (click)="toggleModalTasks(task.title, column.name)">
                <h3 class="h3 text-black">{{task.title}}</h3>
                <p class="body-m text-medium-grey mt-2">
                  {{counter}} of {{ task.subtasks.length }} subtasks
                </p>
              </button>
            }
        </section>
      }
      <button class="mt-8 bg-lines-light rounded-md" >
        <span class="h1 text-medium-grey">New Column</span>
      </button>
    </section>
  }


  @if (isModalTaskOpen) {
    <app-task [board]="board()" [taskTitle]="taskName" [columnName]="columnName"/>
  }

</section>
