// src/app/components/delete-board/delete-board.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-delete-board',
  standalone: true,
  imports: [],
  templateUrl: './delete-board.component.html',
  styleUrl: './delete-board.component.scss'
})
export class DeleteBoardComponent {

}

<div id="static-modal" data-modal-backdrop="static" tabindex="-1" aria-hidden="true" class="overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative p-4 w-full max-w-2xl max-h-full">
      <!-- Modal content -->
      <div class="relative overflow-y-scroll  bg-white rounded-lg shadow p-6 w-[60%] left-[100%] top-28">
          <!-- Modal header -->
          <div class="">
              <h2 class="h2 mr-4 text-red">
                Delete this board?
              </h2>
          </div>
          <!-- Modal body -->
          <p class="mt-6 body-l text-medium-grey">
            Are you sure you want to delete the ‘Platform Launch’ board? This action will remove all columns and tasks and cannot be reversed.
          </p>
          <!-- Modal footer -->
          <div class="flex justify-between mt-4">
            <button class="button-destructive rounded-full w-40">
              Delete
            </button>
            <button class="button-secondary rounded-full w-40">
              Cancel
            </button>
          </div>

      </div>
  </div>
</div>

// src/components/DeleteBoard.tsx
const DeleteBoard = () => {
  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
        <div className="bg-white p-6 rounded-lg w-90 max-h-[90vh] flex flex-col" >
            <h2 className="text-red">Delete this board?</h2>
            <p className='body-l text-medium-grey mt-4'>Are you sure you want to delete the ‘Platform Launch’ board? This action will remove all columns and tasks and cannot be reversed.</p>
            <div className='flex items-center gap-3 mt-6'>
                <button className='button-destructive'>Delete</button>
                <button className='button-secondary'>Cancel</button>
            </div>
        </div>
    </div>
  )
}

export default DeleteBoard
